# Context configuration for feature engineering and prediction
# Mapping of competition IDs to league strength factor
league_strength_map_by_id:
  GB1: 1.0        # Premier League
  ES1: 0.95       # LaLiga
  IT1: 0.95       # Serie A
  DE1: 0.95       # Bundesliga
  FR1: 0.85       # Ligue 1
  NL1: 0.80       # Eredivisie
  PT1: 0.80       # Primeira Liga
  TR1: 0.70       # Süper Lig
  BE1: 0.70       # Belgian Pro League
  RU1: 0.65       # Russian Premier League
  BR1: 0.70       # Brasileirão
  AR1: 0.65       # Liga Profesional (Argentina)

# Default factor for unmapped competitions
default_league_strength_factor: 0.40

# Tier-1 clubs list (can be revisited periodically)
club_tier_1:
  - Real Madrid
  - FC Barcelona
  - Manchester City
  - Liverpool FC
  - Bayern Munich
  - Paris Saint-Germain
  - Arsenal FC
  - Manchester United
  - Chelsea FC
  - Juventus FC
